version: '3.7'

services:
  api:
    build: . 
    container_name: google_news_rss 
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8000:80"
